spring.datasource.url=jdbc:postgresql://db.bembebuyunumtoslmvdn.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=aandreshurtado1233
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
