spring.application.name=lavaca-api
# URL de conexión a tu BD lavaca_db (ajusta el nombre si es otro)
spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/lavaca_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

# Credenciales de acceso
spring.datasource.username=root
spring.datasource.password=

# Control de creación/actualización de tablas
spring.jpa.hibernate.ddl-auto=update

# Dialecto correcto para MariaDB
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# Opcional: mostrar las SQL que se ejecutan
spring.jpa.show-sql=true

